project_id = "evjdmanjcqwvuymrnded"

[functions.generate-text]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.generate-music]
verify_jwt = true

[functions.check-music-status]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.suno-callback]
verify_jwt = false
